version: '3.8'
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/pdf_audit
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
    depends_on:
      - redis
      - minio
      - mlflow
      - clamav
      - postgres

  celery:
    build: .
    command: celery -A tasks.celery worker -l info -c 4 -Q default,high
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/pdf_audit
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
    depends_on:
      - flask
      - redis
      - postgres

  redis:
    image: redis:alpine

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=pdf_user
      - POSTGRES_PASSWORD=9588
      - POSTGRES_DB=pdf_audit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5001:5000"
    command: mlflow server --host 0.0.0.0

  clamav:
    image: clamav/clamav
    ports:
      - "3310:3310"

volumes:
  postgres_data: